### ISSUE TITLE
[QUESTION] Post-validation Optimizer 

### ISSUE THREAD

**Issue by Parallel-Hao** [sail-sg/zero-bubble-pipeline-parallelism#16]
Figure 4 shows there are forward steps (the blue ones) of the next iteration between optimizer steps and post-validation steps.  When validation fails and redo the optimizer steps, is it necessary to redo these forward steps that have used the illegitimate weights?
<img width="657" alt="figure4" src="https://github.com/sail-sg/zero-bubble-pipeline-parallelism/assets/45378899/35d3887d-8295-4d10-9e1c-d4b816f38603">

**Comment by ufotalent** [comment]
Hi, yes it is necessary to redo these forward steps.

In our current implementation if post validation fails we rollback and restart next iteration from a clean state.
