### ISSUE TITLE
[QUESTION] How to avoid synchronization when using sharding

### ISSUE THREAD

**Issue by AndSonder** [sail-sg/zero-bubble-pipeline-parallelism#19]
Hi, I currently want to adapt zbv for Paddle. In your work, the main role of rollback is to reduce synchronization. However, the grad_norm in the opt stage requires all_reduce_sum, and if the sharding strategy is enabled, there is a parameter broadcast operation after the parameter update, which makes it difficult to avoid global communication. Have you tested the hybrid parallel with the sharding strategy? After enabling sharding, is there no way to actually rollback?

**Comment by AndSonder** [comment]
@ufotalent could you help to answer this question please?

**Comment by ufotalent** [comment]
> @ufotalent could you help to answer this question please?
@AndSonder 
Hi, I'm thrilled to know Paddle is integrating our method.

Just to make sure, the sharding refers to data-parallel-style sharding like Zero stage 1? Then the all_reduce communication should be within the DP communication group, so is actually orthogonal to the PP group? That said though, a re-all-gather of parameter will be necessary if a rollback is conducted on local parameters.

Not sure whether this resolves your question. I can also be contacted via WeChat ID ufotalent for a more interactive discussion, if you need. Thanks!

**Comment by AndSonder** [comment]
Thank you very much for your reply. You're right. The all_reduce communication should be within the DP communication group, and is actually orthogonal to the PP group. I will contract you when I meet other problems.
