### ISSUE TITLE
[QUESTION] can ZB work with DeepSpeed (or is there a plan?)

### ISSUE THREAD

**Issue by guoyejun** [sail-sg/zero-bubble-pipeline-parallelism#23]
hi, 

microsoft forks megatron-lm to https://github.com/microsoft/megatron-DeepSpeed, and makes it work together with https://github.com/microsoft/DeepSpeed for a good 3D parallelism (sharded DP, TP and PP).

since this project is also forked from megatron-lm, so is it possible to work with DeepSpeed (may first integrate with megatron-DeepSpeed)?

thanks.

**Comment by ufotalent** [comment]
Hi thanks for the interest in our work. We indeed have an experimental implementation on ZB-H1 on deepspeed-megatron in another repository

https://github.com/microsoft/Megatron-DeepSpeed/compare/main...sail-sg:zero-bubble-megatron-deepspeed:integrated-zbpp

We haven't got it merged into upstream yet. If you're interested I think you can definitely have a try.

**Comment by guoyejun** [comment]
thanks, I'll take a look.

**Comment by guoyejun** [comment]
btw, any simple commands to run PP (for example PP=2) with zero-bubble-megatron-deepspeed for a quick try? thanks.

**Comment by nvmdava** [comment]
Hi, 
Short details regarding the repo for zero-bubble-megatron-deepspeed is written [here as a pull request](https://github.com/microsoft/Megatron-DeepSpeed/pull/396). To run it you can add the flag `--enable-zbh1-pipeline` to their [rebase training scripts](https://github.com/sail-sg/zero-bubble-megatron-deepspeed/tree/main/examples_deepspeed/rebase). 

Let me know if there's anything else you need.

**Comment by QPHutu** [comment]
ZB-H1 has already merged into microsoft Megatron-DeepSpeed in [this commit](https://github.com/microsoft/Megatron-DeepSpeed/pull/396). Welcome to have a try simply adding `--enable-zbh1-pipeline` flag.

Thanks @nvmdava for the great work.
